kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/populatedatabase
  set:
    replicaCount: 1
    image:
      repository: populatedatabase
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
      # This expands to [space.s.]populatedatabase.<guid>.<region>.aksapp.io
      - $(spacePrefix)populatedatabase$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true
    container:
      sync:
      - "!**/package.json"
      iterate:
        processesToKill: [node]
      values:
      - "charts/populatedatabase/values.yaml"