version: '2'

services:
    populatedatabase:
        build: .
        ports:
            - "8080:80"
        environment:
            - filename_data=data.json
            - gateway_dnsname=apigateway:5000