kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/package
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: IfNotPresent
    ingress:
      hosts:
      # This expands to [space.s.]package.<guid>.<region>.aksapp.io
      - $(spacePrefix)package$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true