      # This expands to [space.s.]package.<guid>.<region>.aksapp.io
kind: helm-release
apiVersion: 1.1
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/package
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: IfNotPresent
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      - $(spacePrefix)package$(hostSuffix)
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
configurations:
  develop:
    build:
      useGitIgnore: true
