kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile.develop
  # dockerfile: Dockerfile
install:
  chart: charts\gateway
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: gateway
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
      # This expands to [space.s.]gateway.<guid>.<region>.aksapp.io
      - $(spacePrefix)gateway$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true