# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: reservationengine
replicaCount: 1
image:
  repository: yanambia/contoso-bikerental-reservationengine
  tag: latest
  pullPolicy: Always
imagePullSecrets: []
  
service:
  type: ClusterIP
  port: 80

probes:
  enabled: false

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  path: /
  tls: []

secrets:
    bikes:
      dnsName: bikes
    billing:
      dnsName: billing
    mongo:
      connectionString: mongodb://databases-mongo
      dbName: resdb
      collection: reservation
  
resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}