# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bikesharingweb:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik-azds  # Dev Spaces-specific
    hosts:
      - default.bikesharingweb.llpqkwz856.eus.azds.io  # Assumes deployment to the 'default' space

gateway:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik-azds  # Dev Spaces-specific
    hosts:
      - default.gateway.llpqkwz856.eus.azds.io  # Assumes deployment to the 'default' space