# Default values for populatedatabase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: populatedatabase
replicaCount: 1
image:
  repository: yanambia/contoso-bikerental-populatedatabase
  tag: latest
  pullPolicy: Always
imagePullSecrets: []
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName

env:
  - name: GATEWAY_DNSNAME
    value: gateway
  - name: BIKES_DNSNAME
    value: bikes
  - name: USERS_DNSNAME
    value: users

restartPolicy: Never
backOffLimit: 4

service:
  type: ClusterIP
  port: 80

probes:
  enabled: false

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    # kubernetes.io/tls-acme: "true"
  path: /

secrets: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}