# Default values for bikesharingweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# MUST CHANGE TO THE HOSTNAME FOR THE GATEWAY
apiHost: gateway.64b3949c8c0849ce89b5.eastus.aksapp.io

fullnameOverride: bikesharingweb
replicaCount: 1
image:
  repository: yanambia/contoso-bikerental-bikesharingweb
  tag: latest
  pullPolicy: Always
imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

probes:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  path: /
  hosts:
    - bikesharingweb.64b3949c8c0849ce89b5.eastus.aksapp.io
  
secrets: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}