kind: helm-release
apiVersion: 1.1
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/billing
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to [space.s.]billing.<guid>.<region>.aksapp.io
      - $(spacePrefix)$(rootSpacePrefix)billing$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true
    container: {}
