kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/reservation
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
      # This expands to [space.s.]reservation.<guid>.<region>.aksapp.io
      - $(spacePrefix)reservation$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true
    container:
      values:
        - "charts/reservation/values.yaml"