version: '2'

services:
    users:
        build: .
        ports:
            - "8080:80"
        environment:
            - SQL_USERNAME=SA
            - SQL_PASSWORD=!DummyPassword123!
            - SQL_SERVER=db
            - SQL_DATABASE=tempdb
            - SQL_DATABASE=dummytable
        links:
            - db
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            - SA_PASSWORD=!DummyPassword123!
            - ACCEPT_EULA=Y